version: '3.8'

services:
  worklog-api:
    image: raihanwilly/worklog-api:latest # Use the Docker Hub image
    container_name: worklog-api
    restart: always
    ports:
      - "5000:8080" # HTTP
    volumes:
      - worklog-volume:/app/wwwroot/uploads # Persistent volume for uploads
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    logging:
      driver: "json-file" # Configure logging
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  worklog-volume:
    driver: local # Ensure the volume is named for persistence
