version: '3.8'

services:
  worklog-api:
    image: raihanwilly/worklog-api:latest # Use the Docker Hub image
    container_name: worklog-api
    restart: always
    ports:
      - "5000:8080" # HTTP
      #- "5001:8081" # HTTPS (optional)
     volumes:
      - worklog-volume:/app/wwwroot/uploads # Mount to the uploads directory
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      #- ASPNETCORE_HTTPS_PORTS=8081 # Define the HTTPS port
    logging:
      driver: "json-file" # Configure logging
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  worklog-volume:
    driver: local # Ensure the volume is named for persistence
