services:
  
#  worklog-api:
#      image: worklog-api
#      build: ./Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Superadmin123@ 
      - MSSQL_PID=Developer                     
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: on-failure
  
volumes:
  sqlserver_data:
      