version: '3.8'

services:
  app:
    image: worklog-api:latest
    container_name: worklog-api
    restart: always
    ports:
      - "5000:5000" # Map host port to container port
    volumes:
      - worklog-volume:/app/wwwroot # Mount the volume into the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  worklog-volume:
    driver: local
